Repository simple-icons/simple-icons-website, pull requests merged in 2021-09, with the labels that each got.

#99 Converted menu links into logos
  public/index.pug
  public/stylesheet.css
  tests/e2e.test.js
Labels: enhancement, design

#114 fix links to issue templates in two places
  CONTRIBUTING.md
  public/index.pug
Labels: bug

#110 Custom color sorting implementation to remove black icons from ATF icon list
  package-lock.json
  package.json
  scripts/color-sorting.js
  tests/color-sorting.test.js
  tests/e2e.test.js
  tests/helpers.js
  webpack.config.js
Labels: bug

#111 Adding link to website repository in the footer
  public/index.pug
  public/stylesheet.css
  tests/e2e.test.js
Labels: enhancement
