Repository simple-icons/simple-icons-website, pull requests merged in 2021-07, with the labels that each got.

#83 Improve HTML
  public/index.pug
  tests/dom-utils.test.js
  tests/integration.test.js
  webpack.config.js
Labels: enhancement, performance

#74 Add link to DISCLAIMER.md
  public/index.pug
Labels: design, in discussion

#90 added required CSS reset
  public/stylesheet.css
Labels: design, enhancement

#65 Set up scheduled analysis
  .github/codeql.yml
  .github/workflows/analysis.yml
  lighthouserc.json
Labels: meta

#93 Fix access permission of husky files
  .husky/pre-commit
  .husky/pre-push
Labels: meta
