Repository simple-icons/simple-icons-website, pull requests merged in 2021-08, with the labels that each got.

#98 Fix missing icons bug
  package-lock.json
  package.json
  webpack.config.js
Labels: bug, dependencies

#85 Update search input
  public/index.pug
  public/scripts/search.js
  public/stylesheet.css
  tests/search.test.js
Labels: enhancement

#106 Disable Renovate dependency dashboard
  .github/renovate.json5
Labels: meta
