Repository simple-icons/simple-icons-website, pull requests merged in 2021-05, with the labels that each got.

#56 Update card design
  public/index.pug
  public/scripts/copy.js
  public/stylesheet.css
  tests/copy.test.js
  tests/integration.test.js
Labels: design

#55 Add lazy loading using `loading="lazy"`
  public/index.pug
  public/scripts/copy.js
  public/scripts/index.js
  public/stylesheet.css
  tests/copy.test.js
  tests/mocks/dom.mock.js
  webpack.config.js
Labels: performance

#64 Update header links
  public/index.pug
  tests/integration.test.js
Labels: enhancement

#30 Sticky controls on desktops
  public/index.pug
  public/stylesheet.css
Labels: design

#72 Add fallback fonts and use CSS vars for font families
  public/stylesheet.css
Labels: bug, design

#69 Add content-visibility to grid items
  public/stylesheet.css
Labels: performance

#73 Add Open Collective
  .github/FUNDING.yml
  public/index.pug
Labels: enhancement
