Repository simple-icons/simple-icons-website, pull requests merged in 2021-11, with the labels that each got.

#136 Rewrite test to use `describe.each` instead of `Array.prototype.forEach`
  tests/e2e.test.js
Labels: refactor

#141 Prevent focus on `body`
  public/index.pug
Labels: bug

#140 Prevent focus on hidden copy `input`
  public/index.pug
Labels: bug

#137 Add Windows support for `clean` script
  package.json
Labels: meta, dependencies

#138 Add Pug formatting using Prettier
  package-lock.json
  package.json
  public/index.pug
Labels: meta, dependencies

#139 Produce unminified build on development mode
  webpack.config.js
Labels: meta

#142 Test embedded icons optimization with simple-icons SVGO config
  .editorconfig
  package-lock.json
  package.json
  public/index.pug
  tests/assets.test.js
Labels: dependencies, performance

#108 Alleviate package-lock changing problems
  .npmrc
  .nvmrc
  package.json
Labels: meta

#134 Added 3rd party menu item and corresponding tests
  public/index.pug
  public/scripts/dom-utils.js
  public/scripts/index.js
  public/scripts/modal.js
  public/stylesheet.css
  tests/dom-utils.test.js
  tests/e2e.test.js
  tests/mocks/dom-utils.mock.js
  tests/mocks/dom.mock.js
  tests/modal.test.js
  webpack.config.js
Labels: enhancement

#112 Added a group of buttons for universal download type
  public/index.pug
  public/scripts/download-type.js
  public/scripts/index.js
  public/scripts/storage.js
  public/stylesheet.css
  tests/e2e.test.js
  webpack.config.js
Labels: enhancement

#151 Fix click outside extensions modal not closing it in Firefox
  public/scripts/modal.js
  tests/mocks/dom.mock.js
  tests/modal.test.js
Labels: bug
