Repository simple-icons/simple-icons-website, pull requests merged in 2022-09, with the labels that each got.

#216 Add sitemap
  package-lock.json
  package.json
  public/assets/check-white.svg
  public/assets/check.svg
  public/assets/copy-white.svg
  public/assets/copy.svg
  public/assets/external-link-white.svg
  public/assets/external-link.svg
  public/assets/legal-white.svg
  public/assets/legal.svg
  public/images/logo.svg
  public/sitemap.template.xml
  webpack.config.js
Labels: enhancement, dependencies

#217 Add meta tags for search engines indexation
  public/index.pug
Labels: enhancement

#218 Add localization
  .editorconfig
  CONTRIBUTING.md
  locales/es.po
  locales/fr.po
  locales/languages.json
  package-lock.json
  package.json
  public/index.pug
  public/sitemap.template.xml
  public/stylesheet.css
  scripts/bump-simpleicons.js
  scripts/i18n.js
  tests/copy.test.js
  tests/locales.test.js
  webpack.config.js
Labels: enhancement, design

#221 Fix error serving icons from localized pages
  public/index.pug
Labels: bug

#220 Add linting
  .eslintignore
  .eslintrc.json
  package-lock.json
  package.json
  public/.eslintrc.json
  public/scripts/copy.js
  public/scripts/dom-utils.js
  public/scripts/modal.js
  public/scripts/search.js
  public/scripts/utils.js
  scripts/GET.js
  scripts/bump-simpleicons.js
  scripts/color-sorting.js
  scripts/i18n.js
  tests/.eslintrc.json
  tests/assets.test.js
  tests/e2e.test.js
  tests/helpers.js
  tests/locales.test.js
  tests/mocks/dom.mock.js
  tests/mocks/fetch.mock.js
  tests/search.test.js
  webpack.config.js
Labels: meta, refactor

#228 Fix errors in translations
  locales/es.po
  locales/fr.po
  locales/it.po
  public/index.pug
Labels: i18n

#229 Remove Lighthouse from CI
  .github/workflows/analysis.yml
  lighthouserc.json
Labels: meta

#230 Add permissions to CI workflows
  .github/workflows/analysis.yml
  .github/workflows/auto-release.yml
  .github/workflows/publish.yml
  .github/workflows/verify.yml
Labels: meta

#232 Use common Simple Icons ESLint configuration
  .eslintrc.json
  package-lock.json
  package.json
Labels: meta

#233 Advice about icons that will be removed in next versions
  locales/es.po
  locales/fr.po
  locales/it.po
  public/assets/warning.svg
  public/index.pug
  public/stylesheet.css
  scripts/GET.js
  scripts/https.js
  webpack.config.js
Labels: enhancement, design

#235 Add `zh-CN` translations
  locales/languages.json
  locales/zh-CN.po
  public/stylesheet.css
  scripts/i18n.js
  webpack.config.js
Labels: enhancement, i18n

#240 Fix license type not shown in details modal
  public/scripts/modal.js
Labels: bug

#241 Refactor language selector
  public/index.pug
  public/scripts/index.js
  public/scripts/language-selector.js
  public/stylesheet.css
  webpack.config.js
Labels: refactor

#247 Fix comfortable mode grid alignment in production
  public/index.pug
Labels: bug, design

#249 Fix styling errors in language selector
  public/stylesheet.css
Labels: bug, design

#250 Fix ad alignment in compact layout
  public/index.pug
Labels: bug, design

#251 Fix some styling errors
  public/stylesheet.css
Labels: bug, design
