Repository simple-icons/simple-icons-website, pull requests merged in 2023-04, with the labels that each got.

#281 Add support for copying slug
  public/index.pug
  public/scripts/copy.js
  public/stylesheet.css
  tests/e2e.test.js
Labels: enhancement

#285 Move view icon card path to a `defs` symbol
  public/index.pug
Labels: enhancement, performance

#287 Some mangling, refactoring and fix PDF download
  public/index.pug
  public/scripts/copy.js
  public/scripts/dom-utils.js
  public/scripts/download-type.js
  public/scripts/layout.js
  public/scripts/ordering.js
  public/scripts/search.js
  tests/dom-utils.test.js
  tests/e2e.test.js
  tests/mocks/dom-utils.mock.js
  tests/mocks/dom.mock.js
  tests/ordering.test.js
  tests/search.test.js
Labels: bug, performance

#289 Refactor modal
  public/index.pug
  public/scripts/data.js
  public/scripts/dom-utils.js
  public/scripts/index.js
  public/scripts/modal.js
  public/scripts/search.js
  public/stylesheet.css
  scripts/removed-icons.js
  webpack.config.js
Labels: performance

#290 Generate PDFs on client side
  package-lock.json
  package.json
  public/index.pug
  public/scripts/download-type.js
  public/scripts/modal.js
  public/stylesheet.css
  scripts/color-sorting.js
  webpack.config.js
Labels: enhancement, dependencies

#291 Add intersection observer for lazy loading of images
  locales/es.po
  locales/fr.po
  locales/it.po
  locales/ja-JP.po
  locales/pt.po
  locales/zh-CN.po
  locales/zh-HK.po
  locales/zh-TW.po
  public/index.pug
  public/scripts/index.js
  public/scripts/iobserver.js
  public/stylesheet.css
Labels: design, performance

#292 Fix icon not shown in details modal
  public/index.pug
Labels: bug

#293 Improve design of controls icons
  public/index.pug
  public/stylesheet.css
Labels: design

#296 Use simple-icons SDK
  .eslintignore
  .gitignore
  package-lock.json
  package.json
  scripts/bump-simpleicons.js
  tests/constants.js
  tests/copy.test.js
  webpack.config.js
Labels: dependencies
